version: 2
updates:
- package-ecosystem: docker
  directory: alpine
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: alpine-3.10
  ignore:
  - dependency-name: debian
    versions:
    - "~> 3.10"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: alpine-3.15.0
  ignore:
  - dependency-name: debian
    versions:
    - "~> 3.15.0"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: debian-10
  ignore:
  - dependency-name: debian
    versions:
    - "~> 10.pre.slim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: debian-10.1
  ignore:
  - dependency-name: debian
    versions:
    - "~> 10.1.pre.slim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: debian-10.2
  ignore:
  - dependency-name: debian
    versions:
    - "~> 10.2.pre.slim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: debian-11.1
  ignore:
  - dependency-name: debian
    versions:
    - "~> 11.1.pre.slim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: debian-9.11
  ignore:
  - dependency-name: debian
    versions:
    - "~>9.11.pre.slim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: ubuntu-16.04
  ignore:
  - dependency-name: ubuntu
    versions:
    - "~>16.5"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: ubuntu-18.04
  ignore:
  - dependency-name: ubuntu
    versions:
    - "~>18.5"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: ubuntu-20.04
  ignore:
  - dependency-name: ubuntu
    versions:
    - "~>20.5"
  schedule:
    interval: daily
